flask_qa/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash

from .extensions import db

class doctors(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50))
    password = db.Column(db.String(100))

    @property
    def unhashed_password(self):
        raise AttributeError('Cannot view unhashed password!')

    @unhashed_password.setter
    def unhashed_password(self, unhashed_password):
        self.password = generate_password_hash(unhashed_password)

class patients(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    name_first = db.Column(db.String(50))
    name_last = db.Column(db.String(50))
    dob = db.Column(db.Text)
    email = db.Column(db.String(50))
    address = db.Column(db.String(50))
    phone = db.Column(db.String(50))

flask_qa/__init__.py
from flask import Flask 

from .commands import create_tables
from .extensions import db, login_manager
from .models import doctors
from .routes.main import main

def create_app(config_file='settings.py'):
    app = Flask(__name__)

    app.config.from_pyfile(config_file)

    db.init_app(app)

    login_manager.init_app(app)

    login_manager.login_view = 'main.login'

    @login_manager.user_loader
    def load_user(user_id):
        return doctors.query.get(user_id)

    app.register_blueprint(main)

    app.cli.add_command(create_tables)

    return app

flask_qa/routes/main.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.security import check_password_hash
from sqlalchemy import func

from flask_qa.extensions import db
from flask_qa.models import doctors, patients

main = Blueprint('main', __name__)

@main.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        name = request.form['name']
        password = request.form['password']

        doctor = doctors.query.filter_by(username=name).first()

        if not doctor or not check_password_hash(doctor.password, password):
            flash('Could not login. Please try again or register.')
            return redirect(url_for('main.login'))

        else:
            login_user(doctor)
            return redirect(url_for('main.home'))

    return render_template('login.html')

@main.route('/registerdoctor', methods=['GET', 'POST'])
def registerdoctor():
    if request.method == 'POST':
        name = request.form['name']
        unhashed_password = request.form['password']

        doctor = doctors.query\
        .filter(func.lower(doctors.username)==func.lower(name)).first()

        if not doctor:
            doctor = doctors(
                username=name,
                unhashed_password=unhashed_password,
            )
            db.session.add(doctor)
            db.session.commit()
            return redirect(url_for('main.login'))

        else: 
            flash('User already registered. Login please.')
            return redirect(url_for('main.registerdoctor'))

    return render_template('registerdoctor.html')

@main.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    return render_template('home.html')

@main.route('/registerpatient', methods=['GET', 'POST'])
def registerpatient():
    if request.method == 'POST':
        name_first = request.form['name_first']
        name_last = request.form['name_last']
        dob = request.form['dob']
        email = request.form['email']
        address = request.form['address']
        phone = request.form['phone']

        patient = patients.query\
        .filter(func.lower(patients.email) == func.lower(email))\
        .filter(func.lower(patients.name_first) == func.lower(name_first))\
        .filter(func.lower(patients.name_last) == func.lower(name_last))\
        .first()
        
        if patient:
            flash('Patient has already been registered. Please return the device.')
            return redirect(url_for('main.registerpatient')) 

        else:
            patient_obj = patients(
                name_first=name_first,
                name_last=name_last,
                dob=dob,
                email=email,
                address=address,
                phone=phone,
                )

            db.session.add(patient_obj)
            db.session.commit()

            flash("Patient successfully registered! Please return the device.")
            return redirect(url_for('main.registerpatient'))

    return render_template('registerpatient.html')

@main.route('/patientsearch', methods=['GET', 'POST'])
@login_required
def patientsearch():
    patientsearch = patients.query.all()

    context = {
        'patients' : patientsearch
    }
    return render_template('patientsearch.html', **context)

@main.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.login'))

flask_qa/templates/addpatients.html
{% extends 'base.html' %}
{% block title %}AddPatients{% endblock %}

{% block content %}
      <div class="page-header">
        <h1>Enter Your Information Below</h1>
      </div>
        <div class="row">
          <div class="col-lg-12">
            {% with messages = get_flashed_messages() %}
              {% if messages %}
                <div>{{ messages[0]}}<br><br></div>
              {% endif %}
            {% endwith %}
            <div class="well bs-component">
              <form class="form-horizontal" method="POST" action="{{ url_for('main.addpatients') }}">
                <fieldset>
                  <div class="form-group">
                    <label for="inputName" class="col-lg-2 control-label">First Name</label>
                    <div class="col-lg-10">
                      <input type="text" class="form-control" name="name_first" id="name_first" placeholder="First Name">
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputName" class="col-lg-2 control-label">Last Name</label>
                    <div class="col-lg-10">
                      <input type="text" class="form-control" name="name_last" id="name_last" placeholder="Last Name">
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputName" class="col-lg-2 control-label">Date of Birth</label>
                    <div class="col-lg-10">
                      <input type="date" class="form-control" name="dob" id="dob">
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputName" class="col-lg-2 control-label">Email</label>
                    <div class="col-lg-10">
                      <input type="text" class="form-control" name="email" id="email" placeholder="Email">
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputPassword" class="col-lg-2 control-label">Address</label>
                    <div class="col-lg-10">
                      <input type="text" class="form-control" name="address" id="address"
                              placeholder="Street Address, State, City, Zip">
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputPassword" class="col-lg-2 control-label">Phone Number</label>
                    <div class="col-lg-10">
                      <input type="text" class="form-control" name="pnumber" id="pnumber" placeholder="Phone Number">
                    </div>
                  </div>


                  <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                      <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                  </div>
                </fieldset>
              </form>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

flask_qa/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet">

    <link href="{{ url_for('static', filename='theme.css') }}" rel="stylesheet">
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">MBarara Epilepsy Center</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            {% if not current_user.is_authenticated %}
            <li><a href="{{ url_for('main.login') }}">Login</a></li>
            <li><a href="{{ url_for('main.registerpatient') }}">Register Patient</a></li>
            {% endif %}
            {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('main.home') }}">Home</a></li>
            <li><a href="{{ url_for('main.patientsearch') }}">Patients</a></li>
            <li><a href="{{ url_for('main.logout') }}">Logout</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container theme-showcase" role="main">

      {% block content %}{% endblock %}

    </div> <!-- /container -->

  </body>
</html>

flask_qa/templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

{% block content %}
      <div class="page-header">
        <h1>Upcoming Visits</h1>
      </div>
      <div class="row">
        <div class="col-lg-12">
<!--           <div class="list-group">
            {% for question in questions %}
              <a href="{{ url_for('main.question', question_id=question.id) }}" class="list-group-item">
                <h4 class="list-group-item-heading">{{ question.question }}</h4>
                <p class="list-group-item-text">Asked by: {{ question.asker.name }}</p>
                <p class="list-group-item-text">Answered by: {{ question.expert.name }}</p>
              </a>
            {% endfor %}
          </div> -->
        </div><!-- /.col-lg-12 -->
      </div>
{% endblock %}

flask_qa/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

{% block content %}
      <div class="page-header">
        <h1>Login</h1>
      </div>
        <div class="row">
          <div class="col-lg-12">
            {% with messages = get_flashed_messages() %}
              {% if messages %}
                <div>{{ messages[0]}}<br><br></div>
              {% endif %}
            {% endwith %}
            <div class="well bs-component">
              <form class="form-horizontal" method="POST" action="{{ url_for('main.login') }}">
                <fieldset>
                  <div class="form-group">
                    <label for="inputName" class="col-lg-2 control-label">Username</label>
                    <div class="col-lg-10">
                      <input type="text" class="form-control" name="name" id="inputName" placeholder="Name">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword" class="col-lg-2 control-label">Password</label>
                    <div class="col-lg-10">
                      <input type="password" class="form-control" name="password" id="inputPassword" placeholder="Password">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                      <button type="submit" class="btn btn-primary">Login</button>
                    </div>
                  </div>
                </fieldset>
              </form>
            </div>
            <div><a href="{{url_for('main.registerdoctor')}}">Register a Doctor</a></div>
          </div>
        </div>
      </div>
{% endblock %}

flask_qa/templates/patients.html
{% extends 'base.html' %}
{% block title %}Patients{% endblock %}

{% block content %}
<div class="page-header">
        <h1>Patients</h1>
      </div>
      <div class="row">
<!--         <div class="col-lg-12">
          <div class="list-group">
            {% for user in users %}
              <a href="{{ url_for('main.promote', user_id=user.id) }}" class="list-group-item {% if user.expert %}active{% endif %}">
                <h4 class="list-group-item-heading">{{ user.name }}</h4>
              </a>
            {% endfor %}
          </div> -->
        </div><!-- /.col-lg-12 -->
      </div>
{% endblock %}

flask_qa/templates/patientsearch.html
{% extends 'base.html' %}
{% block title %}Patients{% endblock %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

<link rel="stylesheet" type="text/css" href="../static/datatable.css">
  
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>

<script>
  $(document).ready( function () {
    $('#patient_table').DataTable({
      });
} );
</script>

<style>
  td {
    color:  #000000;
  }
  table {
    font-size: 15px;
  }
</style>
<div class="page-header">
        <h1>Patients</h1>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <br>
          <table id="patient_table" class="display">
            <thead>
              <tr>
                <th>Last Name</th>
                <th>First Name</th>
                <th>DOB</th>
                <th></td>
              </tr>
            </thead>
            <tbody>
              {% for patient in patients %}
                  <tr>
                    <td>{{patient.name_last}}</td>
                    <td>{{patient.name_first}}</td>
                    <td>{{patient.dob}}</td>
                    <td>Medical Info</td>
                  </tr>
              {% endfor %}
            </tbody>
          </table>
          </div>
        </div><!-- /.col-lg-12 -->
      </div>
{% endblock %}

flask_qa/templates/register.html
{% extends 'base.html' %}
{% block title %}Doctor Registration{% endblock %}

{% block content %}
<div class="page-header">
        <h1>Doctor Registration</h1>
      </div>
        <div class="row">
          <div class="col-lg-12">
            {% with messages = get_flashed_messages() %}
              {% if messages %}
                <div>{{ messages[0]}}<br><br></div>
              {% endif %}
            {% endwith %}
            <div class="well bs-component">
              <form class="form-horizontal" method="POST" action="{{ url_for('main.register') }}">
                <fieldset>
                  <div class="form-group">
                    <label for="inputName" class="col-lg-2 control-label">Username</label>
                    <div class="col-lg-10">
                      <input type="text" class="form-control" name="name" id="inputName" placeholder="Name">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword" class="col-lg-2 control-label">Password</label>
                    <div class="col-lg-10">
                      <input type="password" class="form-control" name="password" id="inputPassword" placeholder="Password">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                      <button type="submit" class="btn btn-primary">Register</button>
                    </div>
                  </div>
                </fieldset>
              </form>
            </div>
          </div>
{% endblock %}

flask_qa/templates/registerdoctor.html
{% extends 'base.html' %}
{% block title %}Doctor Registration{% endblock %}

{% block content %}
<div class="page-header">
        <h1>Doctor Registration</h1>
      </div>
        <div class="row">
          <div class="col-lg-12">
            {% with messages = get_flashed_messages() %}
              {% if messages %}
                <div>{{ messages[0]}}<br><br></div>
              {% endif %}
            {% endwith %}
            <div class="well bs-component">
              <form class="form-horizontal" method="POST" action="{{ url_for('main.registerdoctor') }}">
                <fieldset>
                  <div class="form-group">
                    <label for="inputName" class="col-lg-2 control-label">Username</label>
                    <div class="col-lg-10">
                      <input type="text" class="form-control" name="name" id="inputName" placeholder="Name">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword" class="col-lg-2 control-label">Password</label>
                    <div class="col-lg-10">
                      <input type="password" class="form-control" name="password" id="inputPassword" placeholder="Password">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                      <button type="submit" class="btn btn-primary">Register</button>
                    </div>
                  </div>
                </fieldset>
              </form>
            </div>
            <div><a href="{{url_for('main.login')}}">Login</a></div>
          </div>
{% endblock %}

flask_qa/templates/registerpatient.html
{% extends 'base.html' %}
{% block title %}Patient Registration{% endblock %}

{% block content %}
      <div class="page-header">
        <h1>Patient Registration</h1><br><p>Welcome to the MBarara Epilepsy Center! Please fill out the following form to register.</p>
      </div>
        <div class="row">
          <div class="col-lg-12">
            {% with messages = get_flashed_messages() %}
              {% if messages %}
                <div>{{ messages[0]}}<br><br></div>
              {% endif %}
            {% endwith %}
            <div class="well bs-component">
              <form class="form-horizontal" method="POST" action="{{ url_for('main.registerpatient') }}">
                <fieldset>
                  <div class="form-group">
                    <label for="inputName" class="col-lg-2 control-label">First Name</label>
                    <div class="col-lg-10">
                      <input type="text" class="form-control" name="name_first" id="name_first" placeholder="First Name">
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputName" class="col-lg-2 control-label">Last Name</label>
                    <div class="col-lg-10">
                      <input type="text" class="form-control" name="name_last" id="name_last" placeholder="Last Name">
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputName" class="col-lg-2 control-label">Date of Birth</label>
                    <div class="col-lg-10">
                      <input type="date" class="form-control" name="dob" id="dob">
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputName" class="col-lg-2 control-label">Email</label>
                    <div class="col-lg-10">
                      <input type="text" class="form-control" name="email" id="email" placeholder="Email">
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputPassword" class="col-lg-2 control-label">Address</label>
                    <div class="col-lg-10">
                      <input type="text" class="form-control" name="address" id="address"
                              placeholder="Street Address, State, City, Zip">
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputPassword" class="col-lg-2 control-label">Phone Number</label>
                    <div class="col-lg-10">
                      <input type="text" class="form-control" name="phone" id="phone" placeholder="Phone Number">
                    </div>
                  </div>


                  <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                      <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                  </div>
                </fieldset>
              </form>
            </div>
          </div>
        </div>
      </div>
{% endblock %}